-- ====================================================================
-- SMART TERRARIUM IOT DASHBOARD - DATABASE SCHEMA (SUPABASE POSTGRESQL)
-- ====================================================================

-- 1. Bảng lưu trữ nhật ký dữ liệu cảm biến chuỗi thời gian (Time-series)
CREATE TABLE IF NOT EXISTS public.sensor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Ho_Chi_Minh', NOW()) NOT NULL,
    temperature NUMERIC(5, 2) NOT NULL,    -- Nhiệt độ (°C) từ DHT11
    humidity NUMERIC(5, 2) NOT NULL,       -- Độ ẩm không khí (%) từ DHT11
    soil_moisture NUMERIC(5, 2) NOT NULL,  -- Độ ẩm đất (%) từ cảm biến đất
    light_level NUMERIC(7, 2) DEFAULT 0,   -- Cường độ ánh sáng (Lux) từ LDR
    is_dark BOOLEAN DEFAULT FALSE          -- Trạng thái Trời tối / Sáng
);

-- 2. Bảng lưu trữ trạng thái điều khiển thiết bị & cài đặt ngưỡng
CREATE TABLE IF NOT EXISTS public.device_controls (
    id INT PRIMARY KEY DEFAULT 1,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Ho_Chi_Minh', NOW()) NOT NULL,
    system_mode VARCHAR(20) DEFAULT 'auto',    -- 'auto' hoặc 'manual'
    pump_status BOOLEAN DEFAULT FALSE,         -- Trạng thái Bơm M1 (ON/OFF)
    lamp_status BOOLEAN DEFAULT FALSE,         -- Trạng thái Đèn LED L1 (ON/OFF)
    rgb_color VARCHAR(10) DEFAULT '#00FF88',   -- Mã màu LED RGB
    rgb_brightness INT DEFAULT 100,            -- Độ sáng LED RGB (0-100%)
    soil_threshold NUMERIC(5, 2) DEFAULT 35.0, -- Ngưỡng kích hoạt bơm tự động (%)
    temp_max_threshold NUMERIC(5, 2) DEFAULT 38.0 -- Ngưỡng cảnh báo quá nhiệt (°C)
);

-- Chèn 1 bản ghi cấu hình mặc định (nếu chưa có)
INSERT INTO public.device_controls (id, system_mode, pump_status, lamp_status, rgb_color, rgb_brightness, soil_threshold, temp_max_threshold)
VALUES (1, 'auto', FALSE, FALSE, '#00FF88', 100, 35.0, 38.0)
ON CONFLICT (id) DO NOTHING;

-- 3. Bảng lưu trữ nhật ký cảnh báo & sự kiện
CREATE TABLE IF NOT EXISTS public.alert_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Ho_Chi_Minh', NOW()) NOT NULL,
    alert_type VARCHAR(50) NOT NULL,       -- 'HIGH_TEMP', 'DRY_SOIL', 'PUMP_ACTIVE', etc.
    severity VARCHAR(20) DEFAULT 'INFO',   -- 'INFO', 'WARNING', 'CRITICAL'
    message TEXT NOT NULL
);

-- 4. Bật quyền truy cập (Row Level Security & Policies) cho Anon Key
ALTER TABLE public.sensor_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_controls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_logs ENABLE ROW LEVEL SECURITY;

-- Cho phép đọc & ghi công khai bằng Anon Key (hoặc có thể hạn chế tùy chọn)
CREATE POLICY "Public Read/Write sensor_logs" ON public.sensor_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write device_controls" ON public.device_controls FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write alert_logs" ON public.alert_logs FOR ALL USING (true) WITH CHECK (true);

-- 5. KÍCH HOẠT REALTIME WEBSOCKETS CHO CÁC BẢNG TRÊN SUPABASE
ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.device_controls;
ALTER PUBLICATION supabase_realtime ADD TABLE public.alert_logs;
